spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ecommercespring
          uri: lb://ECOMMERCESPRING
          predicates:
          - Path=/USUARIO/**
        - id: shopping-cart
          uri: lb://SHOPPING-CART
          predicates:
          - Path=/cart/**
